/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ModifyDataPanel: typeof import('./src/components/settings/ModifyDataPanel.vue')['default']
    QueryDataPanel: typeof import('./src/components/settings/QueryDataPanel.vue')['default']
    RichTextEditor: typeof import('./src/components/RichTextEditor.vue')['default']
    RiskEvidenceTracker: typeof import('./src/components/RiskEvidenceTracker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    UCheckbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UTree: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tree.vue')['default']
    XmlParserPanel: typeof import('./src/components/settings/XmlParserPanel.vue')['default']
    XMLTreeNode: typeof import('./src/components/XMLTreeNode.vue')['default']
  }
}
